POST http://localhost:3006/register/
Content-Type: application/json

{
  "username": "fine",
  "email": "bieber@gmail.com",
  "mobile": "894798475984",
  "password": "love"
}

###

POST http://localhost:3006/login/
Content-Type: application/json

{
  "username": "fine",
  "password": "love"
}

###


GET http://localhost:3006/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpbmUiLCJpYXQiOjE2NzgxNjM4MTV9.CjOEVCzk2vDYxDDVeB2mKEFuJzqKDiJs1nhe8kpqhkc

###



GET http://localhost:3006/books/1

###

GET http://localhost:3006/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpbmUiLCJpYXQiOjE2NzgxNjM4MTV9.CjOEVCzk2vDYxDDVeB2mKEFuJzqKDiJs1nhe8kpqhkc

###

POST http://localhost:3006/biddetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYXNhbnRoIiwiaWF0IjoxNjc4MzUxNDY2fQ.gCKnrIe3m8j3EOQxOx59am9YnokGWGStQ2TqGqymDPQ
Content-Type: application/json

{
  "mobile": "123456789",
  "bookId": 4,
  "bidAmount": "500",

}

###
GET http://localhost:3006/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYXNhbnRoIiwiaWF0IjoxNjc4MjU2Nzg2fQ.edZKSZgfiTzAkLmefeKWUH7yZVrNjQOaI_zus56iYmw

###

POST http://localhost:3006/sell/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpbmUiLCJpYXQiOjE2NzgxNjM4MTV9.CjOEVCzk2vDYxDDVeB2mKEFuJzqKDiJs1nhe8kpqhkc
Content-Type: application/json

{
  "category": "History",
  "title": "World war",
  "author": "prasanth",
  "description": "It is about our world.",
  "publication_year": "2001",
  "isbn": "01010",
  "printed_price": "300",
  "selling_price": "100",
  "language": "English"
}


###

GET http://localhost:3006/userDetails